plugins {
    id 'application'
    id 'org.springframework.boot'
}

application {
    mainClass = 'kr.hakdang.cassdio.web.CassdioWebApplicationKt'
}

dependencies {
    implementation project(':cassdio-core')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

bootJar {
    mainClass = 'kr.hakdang.cassdio.web.CassdioWebApplicationKt'
    archiveBaseName.set('cassdio')
    archiveVersion.set('')
}

apply from: "${project.rootDir}/cassdio-web/frontend.build.gradle"
