services:
  cassandra:
    image: cassandra:5.0
    container_name: cassdio-cassandra
    ports:
      - "29042:9042"
    environment:
      - "MAX_HEAP_SIZE=2048M"
      - "HEAP_NEWSIZE=512M"
      - "CASSANDRA_CLUSTER_NAME=cassdio"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_RACK=rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: unless-stopped
    networks:
      - cassdio-network
    volumes:
      - cassdio_cassandra_data_1:/var/lib/cassandra
      - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  cassdio_cassandra_data_1:
    driver: local

networks:
  cassdio-network:
    driver: bridge
