spring:
  application:
    name: cassdio-web

cassdio:
  version: 0.1.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
