name: "CI (Server)"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: gradle
        timeout-minutes: 3

      - name: Test
        run: ./gradlew unitTest

  integration-test:
    name: Build on Cassandra
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cassandra-version: [ '3.11', '4.0', '4.1', '5.0' ]
      fail-fast: false
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: gradle
        timeout-minutes: 3

      - name: Use Cassandra ${{ matrix.cassandra-version }}
        run: docker compose -f "docker/docker-compose-cassandra-${{ matrix.cassandra-version }}.yml" up -d --build --wait
        timeout-minutes: 3

      - name: Test
        run: ./gradlew integrationTest
